# Generated by Django 5.2.8 on 2025-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Execution time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_usage',
            field=models.IntegerField(blank=True, help_text='Memory usage in KB', null=True),
        ),
    ]
