# Generated by Django 5.2.8 on 2025-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_add_indexes_for_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, default='', help_text='Initial/template code for users to start with'),
        ),
    ]
