# Generated by Django 5.2.8 on 2025-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_starter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='return_type',
            field=models.CharField(default='void', help_text='Return type of the function (e.g., int, string, void)', max_length=50),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='driver_template',
            field=models.TextField(blank=True, default='', help_text='Driver code template for this language'),
        ),
    ]
