# Generated by Django 5.2.8 on 2025-12-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_return_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.ForeignKey(help_text='The programming language this problem is designed for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.programminglanguage'),
        ),
    ]
