# Generated by Django 5.2.8 on 2025-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(blank=True, help_text='Memory limit in KB', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(blank=True, help_text='Time limit in seconds', null=True),
        ),
    ]
