# Generated by Django 5.2.8 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problemattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='argument_types',
            field=models.JSONField(blank=True, default=list, help_text="List of argument types (e.g., ['int[]', 'int'])"),
        ),
    ]
