# Generated by Django 5.2.8 on 2025-12-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_argument_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemattempt',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='problemattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='problemattempt',
            name='code',
            field=models.TextField(blank=True, default='', help_text='Code for this language attempt'),
        ),
        migrations.AlterField(
            model_name='problemattempt',
            name='language',
            field=models.ForeignKey(default=1, help_text='Language for this specific attempt', on_delete=django.db.models.deletion.PROTECT, to='problems.programminglanguage'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='problemattempt',
            unique_together={('user', 'problem', 'language')},
        ),
    ]
