# Generated by Django 5.2.8 on 2025-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problemattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='return_type',
            field=models.CharField(choices=[('int', 'int'), ('string', 'string'), ('float', 'float'), ('bool', 'bool'), ('void', 'void')], default='void', help_text='Return type of the function (e.g., int, string, void)', max_length=50),
        ),
    ]
