# Generated by Django 5.2.8 on 2025-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_alter_problem_return_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='return_type',
            field=models.CharField(choices=[('int', 'int'), ('string', 'string'), ('float', 'float'), ('boolean', 'boolean'), ('void', 'void')], default='void', help_text='Return type of the function (e.g., int, string, void)', max_length=50),
        ),
    ]
